import 'product_variant.dart';

const List<ProductVariant> initialProductVariants = [
  ProductVariant(
    id: 'product_date_nut_chickpea_100g',
    productName: 'خرمای آجیلی',
    flavor: 'آرد نخودچی',
    packageLabel: '۱۰۰ گرم',
    packageGrams: 100,
    currentSellingPrice: 150000,
  ),
  ProductVariant(
    id: 'product_date_nut_ginger_100g',
    productName: 'خرمای آجیلی',
    flavor: 'زنجبیل',
    packageLabel: '۱۰۰ گرم',
    packageGrams: 100,
    currentSellingPrice: 150000,
  ),
  ProductVariant(
    id: 'product_date_nut_plain_100g',
    productName: 'خرمای آجیلی',
    flavor: 'ساده (پودر نشاسته ذرت)',
    packageLabel: '۱۰۰ گرم',
    packageGrams: 100,
    currentSellingPrice: 150000,
  ),
  ProductVariant(
    id: 'product_date_nut_chickpea_400g',
    productName: 'خرمای آجیلی',
    flavor: 'آرد نخودچی',
    packageLabel: '۴۰۰ گرم',
    packageGrams: 400,
    currentSellingPrice: 780000,
  ),
  ProductVariant(
    id: 'product_date_nut_ginger_400g',
    productName: 'خرمای آجیلی',
    flavor: 'زنجبیل',
    packageLabel: '۴۰۰ گرم',
    packageGrams: 400,
    currentSellingPrice: 780000,
  ),
  ProductVariant(
    id: 'product_date_nut_plain_400g',
    productName: 'خرمای آجیلی',
    flavor: 'ساده (پودر نشاسته ذرت)',
    packageLabel: '۴۰۰ گرم',
    packageGrams: 400,
    currentSellingPrice: 780000,
  ),
  ProductVariant(
    id: 'product_date_nut_chickpea_500g',
    productName: 'خرمای آجیلی',
    flavor: 'آرد نخودچی',
    packageLabel: '۵۰۰ گرم',
    packageGrams: 500,
    currentSellingPrice: 900000,
  ),
  ProductVariant(
    id: 'product_date_nut_ginger_500g',
    productName: 'خرمای آجیلی',
    flavor: 'زنجبیل',
    packageLabel: '۵۰۰ گرم',
    packageGrams: 500,
    currentSellingPrice: 900000,
  ),
  ProductVariant(
    id: 'product_date_nut_plain_500g',
    productName: 'خرمای آجیلی',
    flavor: 'ساده (پودر نشاسته ذرت)',
    packageLabel: '۵۰۰ گرم',
    packageGrams: 500,
    currentSellingPrice: 900000,
  ),
  ProductVariant(
    id: 'product_date_nut_chickpea_1kg',
    productName: 'خرمای آجیلی',
    flavor: 'آرد نخودچی',
    packageLabel: '۱ کیلوگرم',
    packageGrams: 1000,
    currentSellingPrice: 1750000,
  ),
  ProductVariant(
    id: 'product_date_nut_ginger_1kg',
    productName: 'خرمای آجیلی',
    flavor: 'زنجبیل',
    packageLabel: '۱ کیلوگرم',
    packageGrams: 1000,
    currentSellingPrice: 1750000,
  ),
  ProductVariant(
    id: 'product_date_nut_plain_1kg',
    productName: 'خرمای آجیلی',
    flavor: 'ساده (پودر نشاسته ذرت)',
    packageLabel: '۱ کیلوگرم',
    packageGrams: 1000,
    currentSellingPrice: 1750000,
  ),
];
